# Generated by Django 4.0 on 2022-06-23 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medical_history', models.CharField(max_length=65536)),
                ('admission_detail', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='DischargeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_discharge', models.DateField()),
                ('brief_summary', models.CharField(max_length=32768)),
                ('admission_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=1024)),
                ('contact_number', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qualification', models.CharField(max_length=32)),
                ('occupation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=16384)),
                ('symptoms', models.CharField(max_length=16384)),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'WEEKS'), ('MONTHS', 'MONTHS'), ('YEARS', 'YEARS')], max_length=8)),
                ('case_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.casesheet')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemsAndDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=16384)),
                ('discharge_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.dischargedetail')),
                ('sickness', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.sickness')),
            ],
        ),
        migrations.AddField(
            model_name='admissiondetail',
            name='PatientDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patientdetail'),
        ),
        migrations.AddField(
            model_name='admissiondetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.doctordetail'),
        ),
    ]
