# Generated by Django 4.0 on 2022-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissiondetail',
            old_name='PatientDetail',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='occupation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='qualification',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
