# Generated by Django 4.0 on 2022-06-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctordetail_auth_user'),
        ('patients', '0002_rename_patientdetail_admissiondetail_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_detail', to='doctors.doctordetail'),
        ),
        migrations.AlterField(
            model_name='admissiondetail',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admission_detail', to='patients.patientdetail'),
        ),
        migrations.AlterField(
            model_name='casesheet',
            name='admission_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_sheet', to='patients.admissiondetail'),
        ),
        migrations.AlterField(
            model_name='dischargedetail',
            name='admission_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharge_detail', to='patients.admissiondetail'),
        ),
    ]
