# Generated by Django 4.0 on 2022-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_admissiondetail_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickness',
            name='duration_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=8),
        ),
    ]
