# Generated by Django 4.0 on 2022-06-28 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_sickness_duration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsanddiagnosis',
            name='sickness',
        ),
        migrations.AddField(
            model_name='problemsanddiagnosis',
            name='problem',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dischargedetail',
            name='date_of_discharge',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
