# Generated by Django 4.0 on 2022-06-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_problemsanddiagnosis_sickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargedetail',
            name='admission_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharge_detail', to='patients.admissiondetail'),
        ),
    ]
