# Generated by Django 4.0 on 2022-07-08 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_alter_dischargedetail_admission_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbs', models.IntegerField()),
                ('ppbs', models.IntegerField()),
                ('rbs', models.IntegerField()),
                ('hba1c', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Electrolytes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodium', models.IntegerField()),
                ('potassium', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmotionAnalysisAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_movement', models.IntegerField()),
                ('assimilation', models.IntegerField()),
                ('restlessness', models.IntegerField()),
                ('elimination', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.IntegerField()),
                ('cold', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('dryness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LipidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdl', models.IntegerField()),
                ('ldl', models.IntegerField()),
                ('tgld', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiverFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast', models.IntegerField()),
                ('alt', models.IntegerField()),
                ('sgot', models.IntegerField()),
                ('sgpt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganEnergyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=32)),
                ('balance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PanchaBoothas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire', models.IntegerField()),
                ('water', models.IntegerField()),
                ('air', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('akash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RenalFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea', models.IntegerField()),
                ('s_creatinine', models.IntegerField()),
                ('uric_acid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtAnalysisAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight_thought', models.IntegerField()),
                ('spiral_thought', models.IntegerField()),
                ('knotted_thought', models.IntegerField()),
                ('multiple_thought', models.IntegerField()),
                ('dip_thought', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thyroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t3', models.IntegerField()),
                ('t4', models.IntegerField()),
                ('tsh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tridosha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vata', models.IntegerField()),
                ('pita', models.IntegerField()),
                ('kapha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitamin_b', models.IntegerField()),
                ('vitamin_c', models.IntegerField()),
                ('vitamin_d3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PulseDiagnosisInvestigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('oxygen', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('rr_interval', models.IntegerField()),
                ('rr_interval_sec', models.IntegerField()),
                ('admission_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
                ('blood_pressure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodpressure')),
                ('blood_sugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodglucose')),
                ('panchaboothas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.panchaboothas')),
                ('tridosha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.tridosha')),
            ],
        ),
        migrations.CreateModel(
            name='InitialFindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hemoglobin', models.IntegerField()),
                ('wbc', models.IntegerField()),
                ('platelets', models.IntegerField()),
                ('admission_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
                ('blood_glucose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodglucose')),
                ('electrolytes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.electrolytes')),
                ('lft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.liverfunctiontest')),
                ('lipid_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.lipidprofile')),
                ('rft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.renalfunctiontest')),
                ('thyroid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.thyroid')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.vitamin')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutineVitalFindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('oxygen_level', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('admission_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
                ('blood_glucose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodglucose')),
                ('blood_pressure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodpressure')),
            ],
        ),
        migrations.CreateModel(
            name='BodyMindWellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('admission_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.admissiondetail')),
                ('emotion_analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.emotionanalysisassessment')),
                ('organ_energy_balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.organenergybalance')),
                ('thought_analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.thoughtanalysisassessment')),
            ],
        ),
    ]
