# Generated by Django 4.0 on 2022-07-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialfindings',
            old_name='admission_details',
            new_name='admission_detail',
        ),
    ]
