# Generated by Django 4.0 on 2022-07-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_dischargedetail_admission_detail'),
        ('vitals', '0002_rename_admission_details_initialfindings_admission_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialfindings',
            name='admission_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initial_findings', to='patients.admissiondetail'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='blood_glucose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.bloodglucose'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='electrolytes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.electrolytes'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='lft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.liverfunctiontest'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='lipid_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.lipidprofile'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='rft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.renalfunctiontest'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='thyroid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.thyroid'),
        ),
        migrations.AlterField(
            model_name='initialfindings',
            name='vitamin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vitals.vitamin'),
        ),
    ]
